spring.application.name=web-application

spring.datasource.url=jdbc:mysql://localhost:3310/vollmed_web?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=bruno

spring.mvc.hiddenmethod.filter.enabled=true
